[package]
name = "binutils"
version = "0.1.0"
authors = ["Guillaume Valadon <guillaume@valadon.net>"]
description = "FFI bindings for the binutils libraries"
build = "build.rs"

[dependencies]
libc = "0.2.40"

[build-dependencies]
cc = "1.0"
